vars = {
'AINITIAL': '',
'ASTART': '/scratch/p66/hxw599/work/PI-test8/ATM_RUNDIR/um_out/PI-test8.astart', 
'AUSCOM_CPL': 'true',
'DATAW': '{work_path}',
'FASTRUN': 'true',
'IDEALISE': '',
'PAREXE': 'parexe',
'PRINT_STATUS': 'PrStatus_Min',
'RPSEED': '',
'RUNID': 'PI-01',
'TYPE': 'NRUN',
'UM_ATM_NPROCX': '16',
'UM_ATM_NPROCY': '12',
'UM_NAM_MAX_SECONDS': '300',
'UM_NPES': '192',
'UM_SECTOR_SIZE': '2048',
'UM_STDOUT_FILE': 'atm.fort6.pe',

# Config input paths
'UNIT01': '',
'UNIT02': 'prefix',
'UNIT04': 'STASHC', 
'UNIT05': 'namelists',
'UNIT07': 'PI-01.out2',
'UNIT08': '/dev/null',
'UNIT09': 'CONTCNTL',
'UNIT10': 'xhist',
'UNIT11': 'ihist', 
'UNIT12': 'thist',
'UNIT14': 'errflag',
'UNIT15': '',
'UNIT58': '',
'UNIT22': 'INPUT/STASHmaster',
'UNIT57': 'INPUT/spec3a_sw_hadgem1_6on',
'UNIT80': 'INPUT/spec3a_lw_hadgem1_6on',
'STASETS_DIR': 'INPUT/stasets',
'VERT_LEV': 'INPUT/vertlevs_G3',

# Ancillary files
'ARCLBIOG': '/projects/access/data/ancil/HadGEM3_cal365//biogenic_351sm.N96L38',
'BIOMASS': '/g/data/p66/txz599/data/ancil/CMIP6/Bio_1850_ESM1.anc',
'CHEMOXID': '/projects/access/data/ancil/HadGEM3_cal365/sulpc_oxidants_N96_L38',
'DMSCONC': '/projects/access/data/ancil/HadGEM3_cal365//DMS_conc.N96',
'NDEPFIL': '/g/data/p66/txz599/data/ancil/CMIP6/Ndep_1850_ESM1.anc',
'OCFFEMIS': '/g/data/p66/txz599/data/ancil/CMIP6/OCFF_1850_ESM1.anc',
'OZONE': '/g/data/p66/txz599/data/ancil/CMIP6/ozone_1850_ESM1.anc',
'SOOTEMIS': '/g/data/p66/txz599/data/ancil/CMIP6/BC_hi_1850_ESM1.anc',
'SULPEMIS': '/g/data/p66/txz599/data/ancil/CMIP6/scycl_1850_ESM1_v4.anc',
'VEGINIT': '/projects/access/data/ancil/access_v2/cable_vegfunc_N96.anc',
}
